development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url || "redis://localhost:6379/1" %>
  channel_prefix: shopify_app_production
